export enum EActions {
  ADD = 'ADD_TODO',
  STATUS = 'CHANGE_STATUS',
  REMOVE = 'REMOVE_TODO',
  ACTIVE = 'SET_ACTIVE',
  CHECKED = 'TOGGLE_CHECKED',
  TEXT = 'EDIT_TEXT',
  NAME = 'EDIT_NAME',
  CHANGE = 'CHANGE_NEW_TODO'
}
